require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/callsigns', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Callsign. As you add validations to Callsign, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Callsign.create! valid_attributes
      get callsigns_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      callsign = Callsign.create! valid_attributes
      get callsign_url(callsign)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_callsign_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      callsign = Callsign.create! valid_attributes
      get edit_callsign_url(callsign)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Callsign' do
        expect do
          post callsigns_url, params: { callsign: valid_attributes }
        end.to change(Callsign, :count).by(1)
      end

      it 'redirects to the created callsign' do
        post callsigns_url, params: { callsign: valid_attributes }
        expect(response).to redirect_to(callsign_url(Callsign.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Callsign' do
        expect do
          post callsigns_url, params: { callsign: invalid_attributes }
        end.to change(Callsign, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post callsigns_url, params: { callsign: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested callsign' do
        callsign = Callsign.create! valid_attributes
        patch callsign_url(callsign), params: { callsign: new_attributes }
        callsign.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the callsign' do
        callsign = Callsign.create! valid_attributes
        patch callsign_url(callsign), params: { callsign: new_attributes }
        callsign.reload
        expect(response).to redirect_to(callsign_url(callsign))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        callsign = Callsign.create! valid_attributes
        patch callsign_url(callsign), params: { callsign: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested callsign' do
      callsign = Callsign.create! valid_attributes
      expect do
        delete callsign_url(callsign)
      end.to change(Callsign, :count).by(-1)
    end

    it 'redirects to the callsigns list' do
      callsign = Callsign.create! valid_attributes
      delete callsign_url(callsign)
      expect(response).to redirect_to(callsigns_url)
    end
  end
end
